---

- hosts: localhost
  connection: local
  gather_facts: True
  vars_files:
    - group_vars/aws/vars.yml
    - group_vars/aws/vault.yml

  tasks:
    - name: Provision a set of instances
      ec2:
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"
         group: default
         instance_type: t2.nano
         image: "{{ ami_id }}"
         wait: true
         exact_count: 2
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
         region: ap-southeast-2
      register: ec2
